name: deep
description: "Deep Peep — A multi-game offline conversation app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

    - family: NotoSansMalayalam
      fonts:
        - asset: fonts/NotoSansMalayalam-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansMalayalam-Bold.ttf
          weight: 700
